spring:
  datasource:
    url: jdbc:h2:mem:sppodb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console